### ISSUE TITLE
Setup and Configure Database

### ISSUE THREAD

**Issue by orjwan98** [FACK1/KamSafer#18]
We will use PSQL and Sequelize:

- [x] setup tables according to schema
- [x] each table has a model
- [x] setup connection to database 
- [x] create both a local and a remote heroku database

**Comment by Samaamro20** [comment]
![db](https://user-images.githubusercontent.com/35188117/52401812-496b3080-2acb-11e9-88cd-42b7fcdb94f6.jpg)
