### ISSUE TITLE
EndPoints

### ISSUE THREAD

**Issue by shaima96** [FACK1/KamSafer#19]
- [ ]  End points 
 - ``` /login ``` `POST`
  - ``` /cars ``` get list of the cars `GET` return result of  [get  list of all cars and their owners] query as`JSON` .
  - ``` /home ``` response with the app`GET` .
  - ``` /add log```    add new log of a specific car `Post`[add trip log of a car] query . 
  - ``` /logs ```   get logs of a specific car `GET` return result of  [get Logs of a specific car in a month] query as `JSON`.

**Comment by m4v15** [comment]
Just want to flag to all of you that looking at your app and controller there are clearly a lot more end points than this.

You should bear this in mind for future projects, think about what endpoints you didn't realise you need.

Also you should add the endpoints you are making to this issue
