### ISSUE TITLE
 Cars Component 

### ISSUE THREAD

**Issue by Samaamro20** [FACK1/KamSafer#20]
-  Cars Component : when cars components render it have a :
   - [x]   car list : render to car component its a list of car component  in the DB by end point `/cars` get list of the cars  `JSON` data .
- Car Component : is a part of Cars Component 
   - [x] car component : each car is a components has:
     -  car owner
     -  car model
     -  car No

**Comment by m4v15** [comment]
@Samaamro20 is this done?
